---
# ====================================
# Secret cho application
# Chứa sensitive data (JWT secret, etc.)
# ====================================
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: multiexpert
type: Opaque
stringData:
  JWT_SECRET: "k8s-multiexpert-jwt-secret-change-in-production"
