[bastion]
18.143.226.44 ansible_user=ubuntu ansible_ssh_private_key_file=~/AWS/multi-expert.pem

[control_plane]
10.0.137.222 ansible_user=ubuntu

[workers]
10.0.135.17 ansible_user=ubuntu
10.0.151.127 ansible_user=ubuntu

[k8s_cluster:children]
control_plane
workers

[k8s_cluster:vars]
ansible_ssh_private_key_file=~/AWS/multi-expert.pem
ansible_ssh_common_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/AWS/multi-expert.pem -W %h:%p ubuntu@18.143.226.44"
